training_pipeline_config:
  pipeline_name: housing    # name of the pipeline
  artifact_dir: artifact    # folder to store the all the information about the artifact



#data ingestion 
data_ingestion_config:  # folder location 
  dataset_download_url: C:\Users\91822\Desktop\git_hub\Housing_power_consumption_project\dataset\car_dekho.zip  # url detail
  raw_data_dir: raw_data 
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 



# data validation
data_validation_config:   # path for the data validation
  schema_dir: config  # schema directory
  schema_file_name: schema.yaml  # schema file name
  report_file_name: report.json
  report_page_file_name: report.html


# data transfomation
data_transformation_config:
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl


# model tranier
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml



#model evaluation
model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  


# model pusher
model_pusher_config:
  model_export_dir: saved_models
